'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({app,pet,player,panel,surface,showPanel,hidePanel,update,updates,snapshot,root,data,onDragMove,movePet,charactersDirectory,sourceCharactersDirectory,showEditor,getEditor,getPetMenu,getPublisher})=>{
  const out=path.join(root,'tests/results'),checks=[],errors=[];
  const runtime={appPath:app.getAppPath(),electronIsPackaged:app.isPackaged,data,charactersDirectory,sourceCharactersDirectory};
  const js=code=>player.webContents.executeJavaScript(code),ui=code=>panel.webContents.executeJavaScript(code);
  const pause=ms=>new Promise(r=>setTimeout(r,ms));
  const wait=async predicate=>{for(let i=0;i<240;i++){if(await predicate())return;await pause(25);}throw Error('当前客户端验收超时');};
  const rendered=()=>js('Number(document.getElementById("canvas").dataset.frame)||0');
  const populated=()=>js(`(()=>{const c=document.getElementById('canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let count=0;for(let i=3;i<d.length;i+=4)if(d[i]>32)count++;return count>1000;})()`);
  const inside=()=>{const b=player.getBounds(),r=surface.region;return b.x===r.x&&b.y===r.y&&b.width===r.width&&b.height===r.height;};
  for(const view of [player,panel])view.webContents.on('console-message',(_,level,message)=>{if(level>=3)errors.push(message);});
  try{
    panel.setMinimizable(false);panel.setClosable(false);
    await wait(()=>Promise.resolve(surface.hosted));await wait(async()=>await rendered()>1);
    if(process.argv.includes('--verify-installed')){
      await require('./verify-updates.cjs')({panel,player,updates,snapshot,data,out,checks});
      fs.writeFileSync(path.join(out,'当前客户端验收.json'),JSON.stringify({passed:true,runtime,checks},null,2));panel.setClosable(true);app.quit();return;
    }
    if(process.argv.includes('--publisher-check')){
      await require('./verify-publisher.cjs')({panel,getPublisher,root,checks});
      fs.writeFileSync(path.join(out,'当前客户端验收.json'),JSON.stringify({passed:true,runtime,checks},null,2));panel.setClosable(true);app.quit();return;
    }
    await require('./verify-panel.cjs')({panel,player,snapshot,out,checks});
    assert.equal(pet.isVisible(),false);assert.equal(panel.contentView.children.includes(player),true);
    assert.ok(snapshot().characters.length>8,'当前客户端应加载数据目录中的人物');
    const expected=new Set([...JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'),'utf8')).characters.map(c=>c.id),...Object.keys(JSON.parse(fs.readFileSync(path.join(charactersDirectory,'index.json'),'utf8')).installed)]);
    assert.equal(snapshot().characters.length,expected.size);assert.deepEqual(snapshot().packs.warnings,[]);
    await ui("document.querySelector('[data-filter=installed]').click()");
    assert.equal(await ui("document.querySelectorAll('.character-card').length"),expected.size);
    const last=snapshot().characters.at(-1).id;
    await ui(`document.querySelector('.character-card[data-id="${last}"]').click()`);
    await wait(()=>Promise.resolve(snapshot().character.id===last));
    update({character:'hanli'});await wait(async()=>await rendered()>1);
    checks.push(`客户端人物包目录 ${charactersDirectory}，已加载 ${snapshot().characters.length} 人`);
    await ui("document.getElementById('reset-window').click()");await pause(160);assert.ok(Math.abs(panel.getSize()[0]-900)<=2&&Math.abs(panel.getSize()[1]-600)<=2,JSON.stringify(panel.getSize()));
    panel.setSize(1100,720);await pause(120);await ui("document.getElementById('reset-window').click()");await pause(200);assert.ok(Math.abs(panel.getSize()[0]-900)<=2&&Math.abs(panel.getSize()[1]-600)<=2,JSON.stringify(panel.getSize()));
    checks.push('窗口放大后可重置为 900 × 600');
    const panelBounds=()=>ui(`(()=>{const r=document.querySelector('.rack').getBoundingClientRect(),d=document.querySelector('.drawer').getBoundingClientRect();return {rackRight:r.right,drawerLeft:d.left};})()`);
    await wait(async()=>{const p=await panelBounds(),r=surface.region;return r.x>=p.rackRight&&r.x+r.width<=p.drawerLeft;});
    const narrow={...surface.region};
    const occupied=await panelBounds();assert.ok(narrow.x>=occupied.rackRight&&narrow.x+narrow.width<=occupied.drawerLeft);
    await ui("document.getElementById('close-settings').click()");await wait(()=>Promise.resolve(surface.region.width>narrow.width+100));
    const withoutSettings=surface.region.width;
    await ui("document.getElementById('toggle-panels').click()");await wait(()=>Promise.resolve(surface.region.width>withoutSettings+100));
    const expanded={...surface.region};assert.ok(expanded.width>=panel.getContentSize()[0]-20);
    const selectRect=await ui("(()=>{const s=document.getElementById('background'),r=s.getBoundingClientRect();return {x:Math.round(r.right-12),y:Math.round(r.y+r.height/2),tag:s.tagName,display:getComputedStyle(s).display};})()");
    assert.equal(selectRect.tag,'SELECT');assert.notEqual(selectRect.display,'none');
    panel.focus();panel.webContents.focus();
    const choicePoint={x:selectRect.x,y:selectRect.y};
    panel.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...choicePoint});
    panel.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...choicePoint});await pause(150);
    for(const keyCode of ['End','Return']){panel.webContents.sendInputEvent({type:'keyDown',keyCode});panel.webContents.sendInputEvent({type:'keyUp',keyCode});}
    await wait(()=>ui("document.querySelector('.scene').dataset.background==='white'"));
    assert.equal(await ui("document.querySelectorAll('.toolbar-choice').length"),0);
    await ui("document.getElementById('background').value='shop';document.getElementById('background').dispatchEvent(new Event('change'))");
    checks.push('背景为原生纵向下拉菜单，隐藏侧面板后仍能真实点击展开并用键盘选择');
    movePet(-9999,-9999);assert.ok(inside());
    movePet(9999,9999);assert.ok(inside());
    await ui("document.getElementById('toggle-panels').click();document.getElementById('settings').click()");
    await wait(()=>Promise.resolve(surface.region.width===narrow.width));assert.ok(inside());
    checks.push(`互动区域随面板显隐扩展：双面板 ${narrow.width}、收起设置 ${withoutSettings}、隐藏面板 ${expanded.width} DIP；四边可达，恢复后避开面板`);
    assert.deepEqual(await ui("Array.from(document.getElementById('background').options,o=>o.value)"),['shop','black','white']);
    checks.push('背景菜单仅保留店铺、黑、白');
    const paint=()=>js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
    const pixels=()=>js(`(()=>{const c=document.getElementById('canvas'),r=c.getBoundingClientRect(),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let left=c.width,top=c.height,right=0,bottom=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>8){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x+1);bottom=Math.max(bottom,y+1);}return {x:r.x+left*r.width/c.width,y:r.y+top*r.height/c.height,right:r.x+right*r.width/c.width,bottom:r.y+bottom*r.height/c.height,canvasWidth:r.width,canvasHeight:r.height,dpr:devicePixelRatio};})()`);
    update({character:'meining',scale:1,autoPlay:false,playing:false});
    const drop=snapshot().actions.find(a=>a.id===snapshot().interactions.drop);
    update({action:drop.id,frame:drop.count-1,autoPlay:false,playing:false});
    await wait(async()=>await rendered()===drop.count);await paint();
    let actual=await pixels();
    assert.ok(Math.abs(actual.canvasWidth*actual.dpr-drop.width)<1,'主窗口100%必须保持原始像素比例');
    assert.ok(Math.abs(actual.canvasHeight*actual.dpr-drop.height)<1);
    const fullSize={width:actual.canvasWidth,height:actual.canvasHeight};
    movePet(99999,99999);await paint();actual=await pixels();
    assert.ok(actual.bottom>surface.region.height+10,'底部应允许超出并由固定视口裁切');
    assert.ok(actual.right>surface.region.width,'右侧应允许超出并裁切');
    fs.writeFileSync(path.join(out,'尺寸边界-100%-互动区.png'),(await player.webContents.capturePage()).toPNG());
    update({scale:.5});await paint();actual=await pixels();
    assert.ok(Math.abs(actual.canvasWidth-fullSize.width*.5)<.1,'50%应为100%的一半');
    update({scale:1});await paint();
    await ui("document.getElementById('toggle-panels').click()");await wait(()=>Promise.resolve(surface.region.width>narrow.width+100));await paint();actual=await pixels();
    assert.ok(Math.abs(actual.canvasWidth-fullSize.width)<.1,'隐藏面板不能放大人物');
    hidePanel();await paint();actual=await pixels();assert.ok(Math.abs(actual.canvasWidth-fullSize.width)<.1,'桌面与窗口比例相同');
    showPanel();await wait(()=>Promise.resolve(surface.hosted));
    await ui("document.getElementById('toggle-panels').click()");await wait(()=>Promise.resolve(surface.region.width===narrow.width));await paint();
    movePet(-99999,-99999);await paint();actual=await pixels();
    assert.ok(actual.x<0&&actual.y<0,'左上边界也允许部分超出并裁切');
    movePet(99999,99999);await paint();
    const {desktopCapturer:captureBounds}=require('electron');
    panel.focus();await pause(100);
    const boundsSources=await captureBounds.getSources({types:['window'],thumbnailSize:{width:1400,height:1000}});
    const boundsShot=boundsSources.find(source=>source.id===panel.getMediaSourceId());
    if(boundsShot)fs.writeFileSync(path.join(out,'尺寸边界-100%-完整窗口.png'),boundsShot.thumbnail.toPNG());
    checks.push('梅凝100%按原像素显示，50%尺寸减半；面板显隐和回桌面不改变比例；四边溢出由固定视口裁切，画布位置保持不变');
    await js("document.documentElement.style.pointerEvents='none'");await ui("document.documentElement.style.pointerEvents='none'");
    update({character:'ziling',scale:1});
    update({action:snapshot().idleId,autoPlay:false,playing:true,loop:true,frame:0});
    await wait(async()=>await rendered()>1);await paint();
    const idleBounds=surface.bounds();movePet(idleBounds.x,99999);await paint();
    const fixedView={...player.getBounds()};
    const drift=await js(`new Promise(resolve=>{const c=document.getElementById('canvas'),start=performance.now(),initial=c.getBoundingClientRect(),frames=new Set();let maxX=0,maxY=0,samples=0;function sample(now){const r=c.getBoundingClientRect();maxX=Math.max(maxX,Math.abs(r.x-initial.x));maxY=Math.max(maxY,Math.abs(r.y-initial.y));frames.add(c.dataset.frame);samples++;if(now-start>=6500)resolve({maxX,maxY,samples,frames:frames.size,initial:{x:initial.x,y:initial.y,width:initial.width,height:initial.height},final:{x:r.x,y:r.y,width:r.width,height:r.height},host:document.body.dataset.host,action:c.dataset.action});else requestAnimationFrame(sample);}requestAnimationFrame(sample);})`);
    assert.equal(drift.maxX,0,JSON.stringify(drift));assert.equal(drift.maxY,0,JSON.stringify(drift));assert.ok(drift.frames>80,JSON.stringify(drift));
    assert.deepEqual(player.getBounds(),fixedView);assert.ok((await pixels()).bottom>surface.region.height);
    checks.push(`紫灵贴底连续播放 6.5 秒、${drift.frames} 个不同动画帧：画布横纵位移均为 0，越界部分裁切`);
    update({character:'hanli',autoPlay:false,playing:false,frame:15});await wait(async()=>await rendered()===16);await paint();
    const center=()=>js("(()=>{const r=document.getElementById('canvas').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};})()");
    const middle=panel.getContentBounds(),area=surface.region,b=surface.bounds();
    movePet(middle.x+area.x+area.width/2-b.width/2,middle.y+area.y+area.height/2-b.height/2);await paint();
    const scaleCenter=await center();
    for(const percent of [61,100,25,80,100]){
      await ui(`document.getElementById('scale').value='${percent}';document.getElementById('scale').dispatchEvent(new Event('input'))`);
      await wait(()=>Promise.resolve(snapshot().settings.scale===percent/100));await paint();
      const scaled=await center();
      assert.ok(Math.abs(scaled.x-scaleCenter.x)<.05&&Math.abs(scaled.y-scaleCenter.y)<.05,'缩放中心不能漂移：'+JSON.stringify({percent,scaleCenter,scaled}));
    }
    const repositioned=surface.bounds();movePet(repositioned.x+43,repositioned.y+51);await paint();
    const draggedCenter=await center();
    update({scale:.61});await paint();const draggedScaled=await center();
    assert.ok(Math.abs(draggedCenter.x-draggedScaled.x)<.05&&Math.abs(draggedCenter.y-draggedScaled.y)<.05);
    update({scale:1});await paint();
    checks.push('滑条100%→61%→100%及多档缩放中心保持固定；拖到新位置后缩放中心仍不漂移');
    const id=player.webContents.id;await js('window.surfaceSentinel={id:Math.random()};window.surfaceFrames={blank:0,total:0};window.sampleSurface=function(){const c=document.getElementById("canvas");const d=c.getContext("2d").getImageData(0,0,c.width,c.height).data;let has=false;for(let i=3;i<d.length;i+=4){if(d[i]>32){has=true;break;}}window.surfaceFrames.total++;if(!has)window.surfaceFrames.blank++;window.surfaceSampling=requestAnimationFrame(window.sampleSurface)};window.surfaceSampling=requestAnimationFrame(window.sampleSurface)');
    const sentinel=await js('surfaceSentinel.id');
    for(let i=0;i<4;i++){
      update({autoPlay:false,playing:false,action:snapshot().idleId,frame:15});await wait(async()=>await rendered()===16);
      if(i%2){panel.setClosable(true);panel.close();panel.setClosable(false);}else await ui('document.getElementById("hide-panel").click()');
      await wait(()=>Promise.resolve(!surface.hosted));assert.equal(pet.isVisible(),true);assert.equal(pet.contentView.children.includes(player),true);
      assert.equal(snapshot().settings.autoPlay,true);assert.equal(snapshot().settings.playing,true);assert.equal(snapshot().settings.action,snapshot().idleId);
      await wait(async()=>await rendered()>1);const resumed=await rendered();await pause(150);assert.notEqual(await rendered(),resumed,'回到桌面应恢复播放');
      showPanel();await wait(()=>Promise.resolve(surface.hosted));assert.equal(pet.isVisible(),false);
      assert.equal(snapshot().settings.autoPlay,true);assert.equal(snapshot().settings.playing,true);
      assert.equal(player.webContents.id,id);assert.equal(await js('surfaceSentinel.id'),sentinel);
    }
    checks.push('收起和关闭主窗口连续四轮均从手动暂停恢复自动播放；再次打开保持自动播放，复用同一播放页面');
    await js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
    await js("document.documentElement.style.pointerEvents=''");await ui("document.documentElement.style.pointerEvents=''");
    const point=await js(`(()=>{const r=document.getElementById('canvas').getBoundingClientRect();for(let y=Math.max(2,Math.ceil(r.y+r.height*.2));y<Math.min(innerHeight-2,r.bottom-2);y++)for(let x=Math.max(2,Math.ceil(r.x+r.width*.25));x<Math.min(innerWidth-2,r.x+r.width*.75);x++){if([[-1,-1],[1,-1],[-1,1],[1,1],[0,0]].every(([dx,dy])=>window.hitTest(x+dx,y+dy)))return {x,y};}return null;})()`);
    assert.ok(point,'需要实际命中不透明像素的 CSS 坐标');
    player.webContents.focus();player.webContents.sendInputEvent({type:'mouseMove',...point});
    player.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});
    await wait(()=>Promise.resolve(snapshot().interactionPhase==='grab'));
    player.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...point});
    await wait(()=>Promise.resolve(snapshot().interactionPhase==='none'));
    checks.push('真实鼠标事件经透明像素命中进入拎起，松开恢复，前端点击链路通过');
    assert.equal(await js("document.querySelectorAll('#tools,button').length"),0,'悬停不再出现设置和播放按钮');
    hidePanel();await paint();
    const desktopPoint=await js("(()=>{const r=document.getElementById('canvas').getBoundingClientRect();for(let y=Math.ceil(r.y+20);y<r.bottom-20;y++)for(let x=Math.ceil(r.x+20);x<r.right-20;x++)if(window.hitTest(x,y))return {x,y};})()");
    player.webContents.sendInputEvent({type:'mouseMove',...desktopPoint});await pause(100);
    assert.equal(await js("document.querySelectorAll('button,nav').length"),0);
    const openContext=async()=>{const previous=getPetMenu();player.webContents.sendInputEvent({type:'mouseDown',button:'right',clickCount:1,...desktopPoint});player.webContents.sendInputEvent({type:'mouseUp',button:'right',clickCount:1,...desktopPoint});await wait(()=>Promise.resolve(getPetMenu()&&getPetMenu()!==previous));return getPetMenu();};
    update({playing:true});let context=await openContext();assert.deepEqual(context.items.map(item=>item.label),['设置','暂停']);context.closePopup();context.items[1].click();assert.equal(snapshot().settings.playing,false);
    context=await openContext();assert.deepEqual(context.items.map(item=>item.label),['设置','播放']);context.closePopup();context.items[1].click();assert.equal(snapshot().settings.playing,true);
    context=await openContext();context.closePopup();context.items[0].click();await wait(()=>Promise.resolve(surface.hosted));
    checks.push('桌面人物悬停无按钮；真实右键弹出设置与播放/暂停，菜单操作可切换播放并打开主界面');

    for(const character of ['hanli','meining','yinyue']){
      update({character,scale:.8,autoPlay:true,playing:true});await wait(async()=>snapshot().character.id===character&&await rendered()>1);
      assert.ok(inside());assert.equal(await populated(),true);
      await js('window.petAPI.dragStart()');assert.equal(snapshot().interactionPhase,'grab');
      await wait(async()=>await rendered()===1);const b=surface.bounds();
      movePet(b.x-5000,b.y+5000);onDragMove();await wait(async()=>await rendered()>1);assert.ok(inside());
      movePet(b.x+5000,b.y-5000);onDragMove();assert.ok(inside());
      await js('window.petAPI.dragEnd()');await wait(()=>Promise.resolve(snapshot().interactionPhase==='none'));
      assert.equal(snapshot().actions.find(a=>a.id===snapshot().settings.action).role,'idle');
    }
    checks.push('韩立、梅凝、银月：点击拎起、移动摇摆、边界限制、松手下落与恢复待机');
    panel.setSize(820,540);await pause(220);assert.ok(inside());
    await ui("document.getElementById('reset-window').click()");await pause(180);assert.ok(inside());
    await require('./verify-memory.cjs')({app,panel,player,surface,showPanel,hidePanel,update,snapshot,out,checks});
    panel.setClosable(true);panel.setMinimizable(true);
    panel.close();assert.equal(surface.hosted,false);assert.equal(pet.isVisible(),true);showPanel();await wait(()=>Promise.resolve(surface.hosted));
    for(let i=0;i<3;i++){
      panel.minimize();await wait(()=>Promise.resolve(!surface.hosted&&!panel.isVisible()));
      const user32=require('node:module').createRequire(path.join(app.getAppPath(),'main.cjs'))('koffi').load('user32.dll'),isVisible=user32.func('int __stdcall IsWindowVisible(uintptr_t hwnd)');
      assert.equal(isVisible(panel.getNativeWindowHandle().readBigUInt64LE()),0,'最小化后原生窗口必须隐藏，移除任务栏按钮');
      await showPanel();await wait(()=>Promise.resolve(surface.hosted&&panel.isVisible()&&!panel.isMinimized()));
    }
    checks.push('三轮最小化均隐藏原生主窗口和任务栏按钮；设置入口恢复窗口与同一播放器；关闭/重置正常');
    await js('cancelAnimationFrame(window.surfaceSampling)');const samples=await js('surfaceFrames');assert.equal(samples.blank,0);assert.ok(samples.total>20);
    checks.push(`逐显示帧检查 ${samples.total} 帧，画布全透明帧 ${samples.blank}`);
    update({character:'hanli',action:'idle',scale:.8,playing:true,autoPlay:true});await wait(async()=>await rendered()>1);
    const finalContent=panel.getContentBounds(),finalArea=surface.region,finalPet=surface.bounds();
    movePet(finalContent.x+finalArea.x+finalArea.width/2-finalPet.width/2,finalContent.y+finalArea.y+finalArea.height/2-finalPet.height/2);await paint();
    fs.writeFileSync(path.join(out,'当前客户端-主窗口.png'),(await panel.webContents.capturePage()).toPNG());
    fs.writeFileSync(path.join(out,'当前客户端-播放视图.png'),(await player.webContents.capturePage()).toPNG());
    panel.focus();await pause(150);
    const pace=await js('new Promise(resolve=>{let frames=0;const start=performance.now();function sample(now){frames++;if(now-start>1200)resolve({frames,elapsed:now-start,hidden:document.hidden});else requestAnimationFrame(sample);}requestAnimationFrame(sample);})');
    assert.equal(pace.hidden,false);assert.ok(pace.frames>15,JSON.stringify(pace));
    checks.push(`窗口内刷新抽查 ${pace.frames} 帧 / ${Math.round(pace.elapsed)} ms`);
    const {desktopCapturer}=require('electron');
    const sources=await desktopCapturer.getSources({types:['window'],thumbnailSize:{width:1400,height:1000}});
    const native=sources.find(source=>source.id===panel.getMediaSourceId());
    if(native)fs.writeFileSync(path.join(out,'当前客户端-完整窗口.png'),native.thumbnail.toPNG());
    await require('./verify-repair.cjs')({app,panel,player,showEditor,getEditor,update,snapshot,root,data,charactersDirectory,sourceCharactersDirectory,checks});
    await require('./verify-publisher.cjs')({panel,getPublisher,root,checks});
    await require('./verify-remove.cjs')({panel,player,update,snapshot,charactersDirectory,sourceCharactersDirectory,root,checks});
    assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'当前客户端验收.json'),JSON.stringify({passed:true,runtime,checks},null,2));console.log(JSON.stringify({passed:true,runtime,checks}));
  }catch(error){console.error(error);try{fs.writeFileSync(path.join(out,'当前客户端-失败现场.png'),(await Promise.race([panel.webContents.capturePage(),pause(1500).then(()=>{throw Error('失败截图超时');})])).toPNG());}catch{}fs.writeFileSync(path.join(out,'当前客户端验收.json'),JSON.stringify({passed:false,runtime,checks,error:error.stack,errors},null,2));console.error(error);app.exit(1);return;}
  panel.setClosable(true);app.quit();
};
