'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({panel,snapshot,data,out,checks})=>{
 const ui=code=>panel.webContents.executeJavaScript(code),pause=ms=>new Promise(r=>setTimeout(r,ms));
 const wait=async fn=>{for(let i=0;i<600;i++){if(await fn())return;await pause(25);}throw Error('更新验收超时');};
 await wait(()=>ui('!!window.petAPI && document.querySelectorAll(".character-card").length>0'));
 assert.equal(snapshot().development,false);assert.equal(await ui('document.getElementById("development-badge").hidden'),true);
 assert.deepEqual(snapshot().updates.preferences,{autoCharacters:true,autoSoftware:true});
 await ui('document.getElementById("check-character-updates").click()');
 await wait(()=>Promise.resolve(snapshot().updates.characters.updated.includes('梅凝')));
 await wait(()=>Promise.resolve(snapshot().updates.characters.status==='idle'));
 assert.deepEqual(snapshot().updates.characters.failures,[]);
 assert.ok(snapshot().updates.characters.added.includes('更新验收新人物'));
 assert.equal(snapshot().packs.entries.find(p=>p.id==='update-demo').installed,false);
 await ui('document.querySelector(".character-card[data-id=meining]").click()');
 await wait(()=>ui('Array.from(document.getElementById("action").options).some(o=>o.value==="meining-update-test")'));
 checks.push('安装版检查后替换已安装人物，新增动作立即进入播放列表，新人物仅加入可安装列表');
 await ui('document.querySelector(".character-card[data-id=update-demo]").click();document.getElementById("invite").click()');
 await wait(()=>ui('!!document.querySelector(".character-card.installed[data-id=update-demo]") && document.getElementById("transfer").hidden'));
 await ui('document.querySelector(".character-card[data-id=update-demo]").click()');
 await wait(()=>Promise.resolve(snapshot().character.id==='update-demo'));
 assert.ok(snapshot().actions.some(a=>a.id==='update-demo-update-test'));
 checks.push('清单新增人物可以按需下载、安装并播放，无需更新客户端人物列表代码');
 await ui('document.getElementById("check-software-updates").click()');
 await wait(()=>Promise.resolve(snapshot().updates.software.status==='available'));
 assert.equal(snapshot().updates.software.availableVersion,'999.0.0');
 await ui('document.getElementById("download-software").click()');
 await wait(()=>Promise.resolve(snapshot().updates.software.status==='ready'));
 assert.ok(fs.readFileSync(path.join(data,'software-updates/qingzhu-pet-999.0.0-windows-x64-setup.exe')).toString().startsWith('MZ'));
 await ui('document.getElementById("install-software").click()');
 await wait(()=>ui('document.getElementById("error-message").textContent.includes("禁止启动安装程序")'));
 checks.push('软件检查忽略人物发布，下载安装包校验完成；验收模式阻止实际启动安装程序');
 await ui('document.getElementById("auto-character-updates").click();document.getElementById("auto-software-updates").click()');
 await wait(()=>Promise.resolve(!snapshot().updates.preferences.autoCharacters&&!snapshot().updates.preferences.autoSoftware));
 assert.deepEqual(JSON.parse(fs.readFileSync(path.join(data,'updates.json'))),{autoCharacters:false,autoSoftware:false});
 await ui('document.getElementById("error").hidden=true;document.getElementById("software-version").scrollIntoView({block:"center"})');await pause(150);
 fs.writeFileSync(path.join(out,'安装版更新验收.png'),(await panel.webContents.capturePage()).toPNG());
 checks.push('自动人物更新、自动软件检查可分别关闭且设置持久保存');
};
