'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({panel,player,snapshot,out,checks})=>{
  const js=code=>panel.webContents.executeJavaScript(code);
  const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async code=>{for(let i=0;i<100;i++){if(await js(code))return;await pause(50);}throw Error('前端验证超时: '+code);};
  panel.setSize(900,600);await pause(100);
  await wait("document.querySelectorAll('.character-card').length>0");
  await js("document.getElementById('background').value='shop';document.getElementById('background').dispatchEvent(new Event('change'))");
  assert.equal(await js("document.getElementById('settings-drawer').hidden"),false);
  assert.equal(await js("document.querySelectorAll('[data-size]').length"),0);
  assert.equal(await js("document.getElementById('scale').step"),'1');
  const playerId=player.webContents.id;
  const rect=()=>js("(()=>{const r=document.querySelector('.stage').getBoundingClientRect();return [r.x,r.y,r.width,r.height]})()");
  const before=await rect();
  await js("document.getElementById('close-settings').click()");
  assert.ok((await rect())[2]>before[2],'收起设置应释放右侧互动空间');
  await js("document.getElementById('settings').click();document.getElementById('toggle-panels').click()");
  assert.equal(await js("getComputedStyle(document.querySelector('.rack')).display"),'none');
  assert.equal(await js("getComputedStyle(document.querySelector('.scene-tools')).display"),'flex');
  assert.ok((await rect())[2]>before[2]*2,'隐藏面板应释放两侧互动空间');
  await js("document.getElementById('background').value='white';document.getElementById('background').dispatchEvent(new Event('change'))");
  assert.equal(await js("getComputedStyle(document.querySelector('.brand')).display"),'none');
  await pause(100);
  fs.writeFileSync(path.join(out,'青竹桌宠-纯色预览.png'),(await panel.webContents.capturePage()).toPNG());
  await js("document.getElementById('background').value='shop';document.getElementById('background').dispatchEvent(new Event('change'));document.getElementById('toggle-panels').click()");
  checks.push('默认展开设置，眼睛与背景始终可用，纯色隐藏题字，面板显隐扩展互动区域');
  assert.deepEqual(await js("Array.from(document.getElementById('background').options,o=>o.value)"),['shop','black','white']);
  await js("document.getElementById('background').value='black';document.getElementById('background').dispatchEvent(new Event('change'))");
  assert.equal(await js("getComputedStyle(document.querySelector('.scene')).backgroundColor"),'rgb(0, 0, 0)');
  await panel.loadFile(path.join(__dirname,'../app/panel.html'));
  await wait("document.querySelectorAll('.character-card').length>0");
  assert.equal(await js("document.getElementById('background').value"),'black');
  await js("localStorage.setItem('panel-background',JSON.stringify({mode:'custom',color:'#345678'}))");
  await panel.loadFile(path.join(__dirname,'../app/panel.html'));
  await wait("document.querySelectorAll('.character-card').length>0");
  assert.equal(await js("document.getElementById('background').value"),'shop');
  checks.push('仅店铺、黑、白三种背景，重载记忆及旧选项回退通过');

  const expected=snapshot().packs.entries.filter(p=>p.installed).length;
  await js("document.querySelector('[data-filter=installed]').click()");
  assert.equal(await js("document.querySelectorAll('.character-card').length"),expected);
  await js("document.querySelector('[data-filter=available]').click()");
  assert.equal(await js("document.querySelectorAll('.character-card.installed').length"),0);
  await js("document.querySelector('[data-filter=all]').click();document.getElementById('portraits').scrollTop=9999");
  const scroll=await js("document.getElementById('portraits').scrollTop");
  await js("document.querySelector('.character-card:last-child').click()");
  await pause(100);
  assert.equal(await js("document.getElementById('portraits').scrollTop"),scroll);
  await js("document.getElementById('search').value='不存在的人物';document.getElementById('search').dispatchEvent(new Event('input'))");
  assert.equal(await js("document.getElementById('empty').hidden"),false);
  await js("document.getElementById('search').value='';document.getElementById('search').dispatchEvent(new Event('input'));document.querySelector('[data-id=hanli]').click()");
  assert.equal(player.webContents.id,playerId);

  await js("document.getElementById('portraits').scrollTop=0");await pause(60);
  await js("document.getElementById('action-toggle').click()");
  assert.equal(await js("document.querySelector('.ui-select-menu').getAttribute('role')"),'listbox');
  await js("document.querySelector('.ui-select-menu').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  assert.equal(await js("document.activeElement.id"),'action-toggle');
  assert.equal(await js("document.querySelectorAll('.ui-select-menu').length"),0);
  checks.push('单一播放页面，角色筛选/搜索、滚动保留、自绘下拉与键盘关闭通过');
  fs.writeFileSync(path.join(out,'青竹桌宠-前端.png'),(await panel.webContents.capturePage()).toPNG());
};
