'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {loadLibrary}=require('../app/character-packs.cjs');
module.exports=async({app,pet,panel,snapshot,update,root,data,onDragMove})=>{
  const out=path.join(root,'tests/results'),checks=[];
  const js=c=>pet.webContents.executeJavaScript(c),pjs=c=>panel.webContents.executeJavaScript(c);
  const wait=async(fn,ms=180000)=>{const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;if(snapshot().packs.transfer.status==='error'&&snapshot().packs.transfer.message!=='下载已取消')throw new Error(snapshot().packs.transfer.message);await new Promise(r=>setTimeout(r,80));}throw new Error('人物下载窗口验收超时：'+JSON.stringify(snapshot().packs.transfer));};
  try{
    await js("document.documentElement.style.pointerEvents='none'");await pjs("document.documentElement.style.pointerEvents='none'");
    assert.deepEqual(snapshot().characters.map(c=>c.id),['hanli']);
    assert.equal(snapshot().packs.entries.filter(p=>p.installed).length,1);
    assert.equal(await pjs("document.getElementById('clean-noise')===null"),true);
    checks.push('全新数据目录只加载韩立，净化开关已移除');
    await pjs("document.getElementById('manage-packs').click()");
    await wait(()=>pjs(`document.querySelectorAll('#pack-list .pack-row').length===${snapshot().packs.entries.length}`),10000);
    await pjs("document.querySelectorAll('#pack-list .pack-row')[1].querySelector('button').click()");
    await wait(()=>Promise.resolve(snapshot().packs.transfer.status==='downloading'),10000);
    await pjs("document.getElementById('pack-cancel').click()");
    await wait(()=>Promise.resolve(snapshot().packs.transfer.status==='error'),30000);
    assert.deepEqual(snapshot().characters.map(c=>c.id),['hanli']);
    assert.equal(snapshot().packs.entries.find(p=>p.id==='meining').installed,false);
    checks.push('从真实下载入口取消时保留默认人物，可再次下载');
    await pjs("document.querySelectorAll('#pack-list .pack-row')[1].querySelector('button').click()");
    await wait(()=>Promise.resolve(snapshot().characters.some(c=>c.id==='meining')));
    assert.deepEqual(snapshot().characters.map(c=>c.id),['hanli','meining']);
    assert.equal(snapshot().packs.transfer.status,'idle');
    assert.equal(snapshot().packs.entries.filter(p=>p.installed).length,2);
    await wait(()=>pjs("document.getElementById('character').options.length===2"),10000);
    checks.push(process.argv.includes('--verify-packs-local')?'从本地已校验包模拟下载梅凝，校验全部帧并即时刷新菜单':'从 GitHub 实际下载梅凝、验证包和逐帧哈希、安装后立即刷新角色菜单');
    await pjs("document.getElementById('character').value='meining';document.getElementById('character').dispatchEvent(new Event('change'))");
    await wait(()=>Promise.resolve(snapshot().character.id==='meining'),10000);
    await wait(()=>js("document.getElementById('canvas').dataset.action==='meining-idle'&&Number(document.getElementById('canvas').dataset.frame)>1"),10000);
    assert.ok(snapshot().animation.frames.every(f=>!f.cleanedFile));
    const alpha=await js("(()=>{const c=document.getElementById('canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let zero=0,solid=0;for(let i=3;i<d.length;i+=4){if(d[i]===0)zero++;if(d[i]===255)solid++;}return {zero,solid};})()");
    assert.ok(alpha.zero>1000&&alpha.solid>1000);
    checks.push('下载的人物可立即切换、播放净化透明待机');
    await js('window.petAPI.dragStart()');onDragMove();
    await wait(()=>Promise.resolve(!snapshot().settings.playing),10000);
    assert.equal(snapshot().animation.id,'meining-grab');
    await js('window.petAPI.dragEnd()');await wait(()=>Promise.resolve(snapshot().settings.action==='meining-idle'),10000);
    checks.push('下载后无需重启即可使用被抓与下落交互');
    const restarted=loadLibrary(root,data);
    assert.deepEqual(restarted.manifest.characters.map(c=>c.id),['hanli','meining']);
    assert.deepEqual(fs.readdirSync(path.join(data,'downloads')),[]);
    checks.push('安装记录可重新加载且下载临时文件已清理');
    fs.writeFileSync(path.join(out,'人物下载面板.png'),(await panel.webContents.capturePage()).toPNG());
    fs.writeFileSync(path.join(out,'人物下载验收.json'),JSON.stringify({passed:true,checks},null,2));
    console.log(JSON.stringify({passed:true,checks}));
  }catch(error){fs.writeFileSync(path.join(out,'人物下载验收.json'),JSON.stringify({passed:false,checks,error:error.stack},null,2));console.error(error);process.exitCode=1;}
  app.quit();
};
