'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({panel,player,snapshot,data,out,checks})=>{
 const ui=code=>panel.webContents.executeJavaScript(code),pause=ms=>new Promise(r=>setTimeout(r,ms));
 const wait=async fn=>{for(let i=0;i<600;i++){if(await fn())return;await pause(25);}throw Error('更新验收超时');};
 await wait(()=>ui('!!window.petAPI && document.querySelectorAll(".character-card").length>0'));
 assert.equal(snapshot().development,false);assert.equal(await ui('document.getElementById("development-badge").hidden'),true);
 assert.deepEqual(snapshot().updates.preferences,{autoCharacters:true,autoSoftware:true});
 await ui('document.getElementById("check-character-updates").click()');
 await wait(()=>Promise.resolve(snapshot().updates.characters.updated.includes('梅凝')));
 await wait(()=>Promise.resolve(snapshot().updates.characters.status==='idle'));
 assert.deepEqual(snapshot().updates.characters.failures,[]);
 assert.equal(snapshot().character.id,'hanli','后台人物更新不能切换当前播放人物');
 assert.ok(snapshot().updates.characters.added.includes('更新验收新人物'));
 assert.equal(snapshot().packs.entries.find(p=>p.id==='update-demo').installed,false);
 await ui('document.querySelector(".character-card[data-id=meining]").click()');
 await wait(()=>ui('Array.from(document.getElementById("action").options).some(o=>o.value==="meining-update-test")'));
 checks.push('安装版检查后替换已安装人物，新增动作立即进入播放列表，新人物仅加入可安装列表');
 await ui('document.querySelector(".character-card[data-id=update-demo]").click();document.getElementById("invite").click()');
 await wait(()=>ui('!document.getElementById("manual-character").hidden'));
 assert.match(await ui('document.getElementById("error-message").textContent'),/手动下载.*导入/);
 assert.match(await ui('window.petAPI.manualDownload("update-demo")'),/\/update-demo\.qzpet$/);
 assert.equal(snapshot().packs.entries.find(p=>p.id==='update-demo').installed,false);
 const closeRect=await ui('(()=>{const r=document.getElementById("dismiss-error").getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})()');
 assert.ok(closeRect.width>=40&&closeRect.height>=40);
 const viewport=player.getBounds();assert.ok(closeRect.x+closeRect.width<=viewport.x,'提示关闭按钮必须在人物渲染区域之外');
 fs.writeFileSync(path.join(out,'下载失败手动选择.png'),(await panel.webContents.capturePage()).toPNG());
 panel.webContents.sendInputEvent({type:'mouseDown',x:Math.round(closeRect.x+closeRect.width/2),y:Math.round(closeRect.y+closeRect.height/2),button:'left',clickCount:1});
 panel.webContents.sendInputEvent({type:'mouseUp',x:Math.round(closeRect.x+closeRect.width/2),y:Math.round(closeRect.y+closeRect.height/2),button:'left',clickCount:1});
 await wait(()=>ui('document.getElementById("error").hidden'));
 await ui('document.getElementById("probability").dispatchEvent(new Event("input"))');await pause(100);
 assert.equal(await ui('document.getElementById("error").hidden'),true,'关闭提示后状态刷新不得再次弹出');
 assert.equal(await ui('document.getElementById("download-recovery").hidden'),false);
 await ui('document.getElementById("retry-character").click()');
 await wait(()=>ui('!!document.querySelector(".character-card.installed[data-id=update-demo]") && document.getElementById("transfer").hidden'));
 await wait(()=>Promise.resolve(snapshot().character.id==='update-demo'));
 assert.ok(snapshot().actions.some(a=>a.id==='update-demo-update-test'));
 assert.equal(snapshot().settings.autoPlay,true);assert.equal(snapshot().settings.playing,true);
 checks.push('新人物下载完成后自动选中并播放，无需再次点击；后台更新保留当前人物');
 await ui('document.getElementById("check-software-updates").click()');
 await wait(()=>Promise.resolve(snapshot().updates.software.status==='available'));
 assert.equal(snapshot().updates.software.availableVersion,'999.0.0');
 await ui('document.getElementById("download-software").click()');
 await wait(()=>ui('!document.getElementById("manual-software").hidden'));
 assert.match(await ui('document.getElementById("software-status").textContent'),/手动下载最新版安装包/);
 assert.equal(await ui('window.petAPI.manualDownload(null)'),'https://github.com/WuJiaJun1020/qingzhu-pet/releases/latest');
 await ui('document.getElementById("download-software").click()');
 await wait(()=>Promise.resolve(snapshot().updates.software.status==='ready'));
 assert.ok(fs.readFileSync(path.join(data,'software-updates/qingzhu-pet-999.0.0-windows-x64-setup.exe')).toString().startsWith('MZ'));
 await ui('document.getElementById("install-software").click()');
 await wait(()=>ui('document.getElementById("error-message").textContent.includes("禁止启动安装程序")'));
 checks.push('软件检查忽略人物发布，下载安装包校验完成；验收模式阻止实际启动安装程序');
 checks.push('第一次下载失败即显示重试与手动下载；点击重试后成功；提示关闭按钮在人物视图外且关闭后不再重复弹出');
 await ui('document.getElementById("auto-character-updates").click();document.getElementById("auto-software-updates").click()');
 await wait(()=>Promise.resolve(!snapshot().updates.preferences.autoCharacters&&!snapshot().updates.preferences.autoSoftware));
 assert.deepEqual(JSON.parse(fs.readFileSync(path.join(data,'updates.json'))),{autoCharacters:false,autoSoftware:false});
 await ui('document.getElementById("error").hidden=true;document.getElementById("software-version").scrollIntoView({block:"center"})');await pause(150);
 fs.writeFileSync(path.join(out,'安装版更新验收.png'),(await panel.webContents.capturePage()).toPNG());
 checks.push('自动人物更新、自动软件检查可分别关闭且设置持久保存');
};
