'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({panel,player,update,snapshot,charactersDirectory,sourceCharactersDirectory,root,checks})=>{
 assert.notEqual(charactersDirectory,sourceCharactersDirectory);
 const sourceIndex=fs.readFileSync(path.join(sourceCharactersDirectory,'index.json'));
 const index=JSON.parse(fs.readFileSync(path.join(charactersDirectory,'index.json'))),folder=path.resolve(charactersDirectory,index.installed.meining.directory);
 assert.ok(folder.startsWith(path.resolve(charactersDirectory)+path.sep));
 const js=code=>panel.webContents.executeJavaScript(code),pause=ms=>new Promise(r=>setTimeout(r,ms));
 const wait=async predicate=>{for(let n=0;n<200;n++){if(await predicate())return;await pause(25);}throw Error('删除人物包验收超时');};
 update({character:'hanli'});await wait(()=>js("document.getElementById('pack-remove').hidden"));
 await js("document.querySelector('[data-filter=all]').click();document.querySelector('.character-card[data-id=meining]').click()");
 await wait(()=>js("!document.getElementById('pack-remove').hidden"));
 const count=snapshot().characters.length;
 await js("document.getElementById('pack-remove').click()");assert.equal(await js("document.getElementById('remove-confirm').hidden"),false);
 assert.match(await js("document.getElementById('remove-question').textContent"),/梅凝/);
 fs.writeFileSync(path.join(root,'tests/results/当前客户端-删除人物包.png'),(await panel.webContents.capturePage()).toPNG());
 await js("document.getElementById('remove-cancel').click()");assert.equal(fs.existsSync(folder),true);assert.equal(snapshot().characters.length,count);
 await js("document.getElementById('pack-remove').click();document.getElementById('remove-accept').click()");
 await wait(()=>Promise.resolve(snapshot().characters.length===count-1));
 await wait(()=>js("document.getElementById('remove-confirm').hidden"));
 assert.equal(snapshot().character.id,'hanli');assert.equal(snapshot().settings.character,'hanli');assert.equal(fs.existsSync(folder),false);
 assert.equal(JSON.parse(fs.readFileSync(path.join(charactersDirectory,'index.json'))).installed.meining,undefined);
 await js("document.querySelector('[data-filter=available]').click();document.querySelector('.character-card[data-id=meining]').click()");
 assert.equal(await js("document.getElementById('invite').textContent"),'安装人物');assert.equal(await js("document.getElementById('pack-remove').hidden"),true);
 await wait(()=>Promise.resolve(!player.getVisible()));
 assert.equal(await js("document.querySelectorAll('.stage canvas,.stage img,#portrait-preview').length"),0);
 await js("document.getElementById('background').value='white';document.getElementById('background').dispatchEvent(new Event('change'));document.getElementById('toggle-panels').click()");
 assert.equal(player.getVisible(),false,'背景或面板显隐不能让未安装人物出现');
 await js("document.getElementById('toggle-panels').click();document.getElementById('background').value='shop';document.getElementById('background').dispatchEvent(new Event('change'))");
 fs.writeFileSync(path.join(root,'tests/results/当前客户端-未安装人物空背景.png'),(await panel.webContents.capturePage()).toPNG());
 await js("document.querySelector('[data-filter=all]').click();document.querySelector('.character-card[data-id=hanli]').click()");
 await wait(()=>Promise.resolve(player.getVisible()));
 checks.push('未安装人物仅保留列表头像，背景区域为空；切换背景和隐藏面板不显示人物，切回已安装人物恢复动画');
 assert.deepEqual(fs.readFileSync(path.join(sourceCharactersDirectory,'index.json')),sourceIndex);
 assert.equal(fs.existsSync(path.join(sourceCharactersDirectory,JSON.parse(sourceIndex).installed.meining.directory)),true);
 checks.push('删除入口保护内置韩立；确认可取消；删除当前人物清除包和索引并切回韩立，未安装列表可重新安装；日常人物包未改动');
};
