const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('petAPI', {
  frameEditor: {
    open:()=>ipcRenderer.invoke('editor-open'),
    list:()=>ipcRenderer.invoke('editor-list'),
    load:(action,index)=>ipcRenderer.invoke('editor-load',action,index),
    saveBatch:items=>ipcRenderer.invoke('editor-save-batch',items),
    onConfirmClose:fn=>ipcRenderer.on('editor-confirm-close',fn),
    cancelClose:()=>ipcRenderer.invoke('editor-cancel-close'),
    discardClose:()=>ipcRenderer.invoke('editor-discard-close')
  },
  snapshot: () => ipcRenderer.invoke('snapshot'),
  openPublisher: () => ipcRenderer.invoke('developer-publisher'),
  configure: patch => ipcRenderer.invoke('configure', patch),
  removeCharacter: id => ipcRenderer.invoke('pack-remove',id),
  installCharacter: id => ipcRenderer.invoke('pack-install',id),
  checkCharacterUpdates: () => ipcRenderer.invoke('pack-check-updates'),
  updateCharacter: id => ipcRenderer.invoke('pack-update',id),
  updatePreferences: patch => ipcRenderer.invoke('update-preferences',patch),
  checkSoftware: () => ipcRenderer.invoke('software-check'),
  downloadSoftware: () => ipcRenderer.invoke('software-download'),
  installSoftware: () => ipcRenderer.invoke('software-install'),
  cancelSoftware: () => ipcRenderer.invoke('software-cancel'),
  importCharacter: () => ipcRenderer.invoke('pack-import'),
  cancelDownload: () => ipcRenderer.invoke('pack-cancel'),
  panel: () => ipcRenderer.invoke('panel'),
  contextMenu: () => ipcRenderer.invoke('pet-context-menu'),
  hidePanel: () => ipcRenderer.invoke('panel-hide'),
  resetPanelSize: () => ipcRenderer.invoke('panel-reset-size'),
  playerRegion: rect => ipcRenderer.invoke('player-region',rect),
  previewVisible: visible => ipcRenderer.invoke('player-preview-visible',visible),
  onPlayerHost: fn => ipcRenderer.on('player-host',(_,mode)=>fn(mode)),
  onPlayerLayout: fn => ipcRenderer.on('player-layout',(_,placement)=>fn(placement)),
  quit: () => ipcRenderer.invoke('quit'),
  dragStart: () => ipcRenderer.invoke('drag-start'),
  dragEnd: () => ipcRenderer.invoke('drag-end'),
  ended: revision => ipcRenderer.invoke('ended', revision),
  progress: (frame, revision) => ipcRenderer.send('progress', frame, revision),
  onState: fn => ipcRenderer.on('state', (_, s) => fn(s)),
  onProgress: fn => ipcRenderer.on('progress', (_, f) => fn(f)),
  onDragEnd: fn => ipcRenderer.on('drag-end', fn)
});
